version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  redis:
    container_name: redis
    image: redis:7.2.5
    restart: always
    ports:
      - '6379:6379'