### CEO 회원가입
POST http://localhost:8080/api/ceos
Content-Type: application/json

{
  "account": "ceo",
  "password": "ceo",
  "name": "ceo",
  "birth": "ceo",
  "phoneNumber": "ceo",
  "email": "ceo"
}

### CEO 로그인
POST http://localhost:8080/api/ceos/login
Content-Type: application/json

{
  "account": "ceo",
  "password": "ceo"
}
