### 회원가입
POST http://localhost:12290/auth/sign-up
Content-Type: application/json

{
  "email": "testest@testest.com",
  "password": "zzz1234"
}

### 로그인
POST http://localhost:12290/auth/sign-in
Content-Type: application/json

{
  "email": "testest@testest.com",
  "password": "zzz1234"
}
